/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TRACKER_POSE_PB_H_INCLUDED
#define PB_TRACKER_POSE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _TrackerPose {
    uint32_t step_index;
    float angle_deg;
    float roll;
    float pitch;
    float yaw;
    uint32_t timestamp_ms;
} TrackerPose;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TrackerPose_init_default                 {0, 0, 0, 0, 0, 0}
#define TrackerPose_init_zero                    {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define TrackerPose_step_index_tag               1
#define TrackerPose_angle_deg_tag                2
#define TrackerPose_roll_tag                     3
#define TrackerPose_pitch_tag                    4
#define TrackerPose_yaw_tag                      5
#define TrackerPose_timestamp_ms_tag             6

/* Struct field encoding specification for nanopb */
#define TrackerPose_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   step_index,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    angle_deg,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    roll,              3) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch,             4) \
X(a, STATIC,   SINGULAR, FLOAT,    yaw,               5) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      6)
#define TrackerPose_CALLBACK NULL
#define TrackerPose_DEFAULT NULL

extern const pb_msgdesc_t TrackerPose_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TrackerPose_fields &TrackerPose_msg

/* Maximum encoded size of messages (where known) */
#define TRACKER_POSE_PB_H_MAX_SIZE               TrackerPose_size
#define TrackerPose_size                         32

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
